channels:
- conda-forge
dependencies:
- python=3.8
- pip>=23.0
- pip:
  - mlflow==2.9.1
  - cloudpickle==2.2.1
  - dataclasses==0.6
  - importlib-metadata==7.0.0
  - numpy==1.22.0
  - packaging==23.2
  - pandas==1.3.5
  - psutil==5.8.0
  - pyyaml==6.0.1
  - scikit-learn==1.1.3
  - scipy==1.10.0
  - skforecast==0.11.0
name: mlflow-env
